nicslu: 
	icc nicslu.c -O3 -I ../include -L ../lib64 -lnicslu -o nicslu -Wl,-rpath=../lib64 -fopenmp

ssn_column_storage_multi_row_computing:
	icc sn_main_column_storage_multi_row_computing.c sn_computing_column_storage_multi_row.c -O3 -I ../include -L ../lib64 -lnicslu -o ssn_column_storage_multi_row_computing -Wl,-rpath=../lib64 -fopenmp 




